version: '3.8'

services:
  vnollx:
    image: vnollx/vnollxai:latest
    container_name: vnollx
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - mysql
      - redis

  mysql:
    image: mysql:8.0
    container_name: vnollxai-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ab147890
      MYSQL_DATABASE: aichat
    volumes:
      - mysql-data:/var/lib/mysql
    command:
      - --default-authentication-plugin=mysql_native_password
    networks:
      - app-network

  redis:
    image: redis:latest
    container_name: vnollxai-redis
    networks:
      - app-network

volumes:
  mysql-data:
    driver: local

networks:
  app-network:
    driver: bridge